"""Depth Sampling Engine.

This module provides the logic to sample Depth Anything V2 depth maps
using boolean masks generated by SAM2, computing robust statistics for
each segmented object.
"""

from __future__ import annotations

from vegetation_analysis.depth_sampling.constants import (
    CENTROID_COLOR,
    CENTROID_RADIUS,
    DEFAULT_EROSION_ITERATIONS,
    DEFAULT_EROSION_KERNEL_SIZE,
    MIN_ERODED_PIXELS,
)
from vegetation_analysis.depth_sampling.sampler import DepthSampler
from vegetation_analysis.depth_sampling.schemas import (
    DepthSamplingResult,
    ImageMetadata,
    SampledObject,
)
from vegetation_analysis.depth_sampling.visualization import DepthSamplingVisualizer

__all__ = [
    "CENTROID_COLOR",
    "CENTROID_RADIUS",
    "DEFAULT_EROSION_ITERATIONS",
    "DEFAULT_EROSION_KERNEL_SIZE",
    "MIN_ERODED_PIXELS",
    "DepthSampler",
    "DepthSamplingResult",
    "DepthSamplingVisualizer",
    "ImageMetadata",
    "SampledObject",
]
